# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Code for Boulder
email: hi@codeforboulder.org
description: > # this means to ignore newlines until "baseurl:"
  Enabling community members to collaboratively solve local problems with technology. 
  We are community organizers, subject-matter experts, designers, technologists, UX/UI experts, interested residents, 
  and more who are working for a better Boulder, a better America and a better tomorrow.
  We are the Boulder brigade of Code for America, a non-partisan, non-political organization working to create low-risk settings 
  for innovation between citizens and government.
# baseurl: "" # the subpath of your site, e.g. /blog
url: "http://designesse.github.io/CodeForBoulder/_site" # the base hostname & protocol for your site, e.g. http://example.com
logo: "/assets/img/CodeForBoulder-Logo-with-Name.png"

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lo
include: ["_pages"]
collections:
  pages:
    output: true
    permalink: /:path/
  current-projects:
  featured-projects:

sass:
  sass_dir: assets/_sass
